version: '{build}'
clone_folder: C:\wafter
init:
- ps: >-
    Install-Product node $env:nodejs_version $env:platform
environment:
  nodejs_version: 12
platform:
  - x86
  - x64
install:
- ps: >-
    $version = (Get-Content package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"

    Update-AppveyorBuild -Version "$version.$env:APPVEYOR_BUILD_NUMBER"
- cmd: >-
    npm ci
before_build:
- ps: >-
    .\hestia.ps1 > $null
build_script:
- cmd: >-
    set NODE_ENV=production

    npm run pkg

    cd dist\

    7z a "wafter-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip" wafter.exe
test: off
artifacts:
- path: dist\wafter-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip
  name: Wafter-%PLATFORM%