version: 1.{build}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
clone_folder: C:\wafter
init:
- ps: >-
    Install-Product node $env:nodejs_version $env:platform
environment:
  nodejs_version: 10
platform:
  - x86
  - x64
install:
- ps: >-
    $repo = "vnma0/hestia"

    $releases_url = "https://api.github.com/repos/$repo/releases/latest"

    Write-Host Determining latest release of Hestia
    $get_res = (Invoke-WebRequest $releases_url | ConvertFrom-Json)
    Write-Host Hestia: $get_res.tag_name

    Write-Host Downloading latest release
    $asset_name = $get_res.assets[0].name
    $asset_url = $get_res.assets[0].browser_download_url
    Invoke-WebRequest $asset_url -Out $asset_name

    Write-Host Extracting latest release
    Remove-Item -path .\public -Recurse -Force
    Expand-Archive $asset_name -DestinationPath .\public
    Remove-Item $asset_name

    Write-Host Successfully installed Hestia

    cd ..\wafter

    npm install
build_script:
- cmd: >-
    npm run pkg

    cd dist\

    7z a "wafter-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip" wafter.exe
test: off
artifacts:
- path: dist\wafter-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip
  name: Wafter-%PLATFORM%